---
title: Practoraat Interactieve Technologie
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: wvginneken@roctilburg.nl

description: Welkom op de testpagina van de Kopgroep Interactieve Technologie. Deze kopgroep bestaat o.a. uit een groep docenten van het ROC Tilburg die experimenteren met nieuwe technologie en media voor het MBO zoals virtual reality en augmented reality. Hier kun je enkele voorbeelden en experimenten zien die gemaakt zijn door de leden. Je kunt sommige 3D modellen op je telefoon in augmented reality zien. Wat we met deze experimenten willen bereiken zijn manieren om leren effectiever en aantrekkelijk te maken voor het onderwijs van nu en de toekomst.
baseurl: ''
url: ''

twitter_username: 
github_username: wvg88
theme: minima
plugins:
- jekyll-feed
